# Retail Sales Analysis using NumPy, Pandas
### A Classroom Data Analytics Project  Superstore Dataset

Course Level: Post NumPy & Pandas Fundamentals
Tools: Python, NumPy, Pandas, Matplotlib

In this project, you'll analyze the Superstore dataset (2014–2017) to solve real business problems using Python. Instead of focusing only on syntax, you'll use data analysis to identify profitable products, evaluate regional performance, analyze sales trends, and perform time series analysis to understand business growth.

Topics Covered
Data Loading & Inspection
Data Cleaning
NumPy Analysis
Business Insights (Category, Product, Customer & Region)
Time Series Analysis (Monthly Trends, Resampling, Rolling Average, Growth Rate)
Business Recommendations & Practice Questions

## 1. Setting Up

** Before an analyst opens a single file, they set up their toolkit. We'll do
the same  nothing fancy, just the libraries this whole notebook depends on.

**What are we going to do?** Import Pandas and NumPy.

**Why is this important?** Every line of analysis below depends on these two imports. Doing it
once, at the top, keeps the notebook clean and predictable.

In [56]:
import numpy as np
import pandas as pd

In [57]:
pd.set_option("display.float_format", lambda x:f"{x:,.2f}")

## 2. Loading the Dataset

 The Superstore's sales team has exported four years of order-level
transactions into a single CSV file, and handed it to you, the analyst, to make sense of.

**What are we going to do?** Read the CSV into a DataFrame using `read_csv()`.

**Why is this important?** Nothing in this project happens until the raw data is sitting in
memory as a DataFrame. We also pass `encoding="latin1"` because Superstore exports commonly
contain characters that break the default UTF-8 reader.

In [58]:
df = pd.read_csv("Superstore (2).csv",encoding="latin1")

## 3. First Look at the Data

 Before trusting any numbers a client will see in a report, an analyst
always checks the shape, structure, and health of the raw data first.

**What are we going to do?** Check `shape`, `columns`, `dtypes`, `info()`, and `describe()`.

**Why is this important?** These five checks answer: *How big is this dataset? What fields do I
have? Are numbers stored as numbers? Are there obvious data quality issues?* Skipping this step is
how analysts end up presenting broken numbers.

In [59]:
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,06/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9845 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9845 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [61]:
df.shape

(9994, 21)

In [62]:
df.describe()

        Row ID  Postal Code     Sales  Quantity  Discount    Profit
count 9,994.00     9,994.00  9,845.00  9,994.00  9,994.00  9,845.00
mean  4,997.50    55,190.38    229.19      3.79      0.16     28.17
std   2,885.16    32,063.69    623.50      2.23      0.21    225.93
min       1.00     1,040.00      0.44      1.00      0.00 -6,599.98
25%   2,499.25    23,223.00     17.24      2.00      0.00      1.75
50%   4,997.50    56,430.50     54.34      3.00      0.20      8.69
75%   7,495.75    90,008.00    209.79      5.00      0.20     29.36
max   9,994.00    99,301.00 22,638.48     14.00      0.80  8,399.98

In [63]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

## 4. Cleaning the Data

 A client will not trust a report built on a dataset nobody bothered to
clean. Before any analysis, we confirm there are no missing values, no duplicate orders, that
every column is stored as the right type, and that column names are easy to work with.

**What are we going to do?** Run `isnull()`, `fillna()` (as a safety net), `drop_duplicates()`,
`astype()`, and `rename()`.

**Why is this important?** Clean, well-typed, consistently-named columns are what make every
later `groupby`, `loc`, and time series operation reliable instead of fragile.

In [64]:
df.isnull().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City               0
State              0
Postal Code        0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales            149
Quantity           0
Discount           0
Profit           149
dtype: int64

In [65]:
df['Sales'] = df['Sales'].fillna(0)

In [66]:
df['Profit'] = df['Profit'].fillna(0)

In [67]:
df.duplicated().sum()

np.int64(0)

In [68]:
df = df.rename(columns = {
    "Order ID" : "Order_ID",
    "Order Date" : "Order_Date",
    "Ship Date" : "Ship_Date",
    "Ship Mode" : "Ship_Mode",
    "Customer ID" : "Customer_ID",
    "Customer Name" : "Customer_Name",
    "Postal Code" : "Postal_Code",
    "Product ID" : "Product_ID",
    "Sub-Category" : "Sub_Category",
    "Product Name" : "Product_Name",
})

In [69]:
df['Postal_Code'] = df['Postal_Code'].astype(str)

In [70]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'],format = "%m/%d/%Y")

In [71]:
df['Ship_Date'] = pd.to_datetime(df['Ship_Date'],format = "%m/%d/%Y")

## 5. A Quick NumPy Refresher Applied to Real Business Numbers

 Before jumping into Pandas-heavy analysis, let's ground ourselves with the
NumPy concepts you already know, but now applied directly to Superstore numbers instead of toy
arrays.

**What are we going to do?** Use `np.unique()`, `np.sort()`, broadcasting, and NumPy aggregation
functions on Sales, Profit, and Category data.

**Why is this important?** Pandas is built on top of NumPy  every column here *is* a NumPy
array underneath. Seeing that link clearly makes both tools easier to reason about together.

In [72]:
regions = np.unique(df['Region'].values)
regions

array(['Central', 'East', 'South', 'West'], dtype=object)

In [73]:
sales_array = df['Sales'].values

In [74]:
top_5 = np.sort(sales_array)[-5:]
top_5

array([10499.97 , 11199.968, 13999.96 , 17499.95 , 22638.48 ])

In [75]:
avg_sales = np.mean(sales_array)
avg_sales

np.float64(225.76829028417055)

In [76]:
min_sales = np.min(sales_array)
min_sales

np.float64(0.0)

In [77]:
max_sales = np.max(sales_array)
max_sales

np.float64(22638.48)

In [78]:
total_sales = np.sum(sales_array)
total_sales

np.float64(2256328.2931000004)

In [79]:
max_profit = np.max(df["Profit"].values)
min_profit = np.min(df["Profit"].values)
print(max_profit)
print(min_profit)

8399.976
-6599.978

In [80]:
net_price_array = df['Sales'].values * (1-df['Discount'].values)
df["net_price_after_dis"] = net_price_array

In [81]:
df.head()

,Row ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,net_price_after_dis
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,261.96
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,731.94
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,14.62
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03,526.67
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,17.89

## 6. Business Question 1  Which Category Generated the Highest Sales?

 The merchandising team wants to know, of Furniture, Office Supplies, and
Technology, which category is actually carrying the business.

**What are we going to do?** Group orders by `Category`, sum their Sales, and sort the result.

**Why is this important?** Category-level revenue is the first cut every retail business reviews
before deciding where to invest in inventory and marketing.

In [82]:
category_sales = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
category_sales

Category
Technology        818,554.82
Furniture         724,234.30
Office Supplies   713,539.18
Name: Sales, dtype: float64

In [83]:
category_share = (category_sales / category_sales.sum() * 100).round(2)
category_share

Category
Technology        36.28
Furniture         32.10
Office Supplies   31.62
Name: Sales, dtype: float64

**Business Insight:** The three categories are much closer in share than most people would
assume — this is a genuinely diversified revenue base, not a single-product business.

## 7. Business Question 2 — Which Sub-Category Generated the Highest Profit?

**Business Scenario:** High sales doesn't always mean high profit. Finance wants to know which
*sub*-category (a more granular cut, like Chairs or Tables within Furniture) actually drops the
most money to the bottom line — and which ones might be quietly losing money.

**What are we going to do?** Group by `Sub_Category`, aggregate Sales and Profit together with
`agg()`, and sort by Profit.

**Why is this important?** Sales and Profit can tell completely different stories at this level
of detail — this is where a business finds its real winners and losers.

In [84]:
subcat_per = df.groupby(["Category","Sub_Category"]).agg(
    total_sales = ("Sales",'sum'),
    total_profit = ("Profit",'sum')
).sort_values("total_profit",ascending = False)

In [85]:
subcat_per

                              total_sales  total_profit
Category        Sub_Category
Technology      Copiers        149,528.03     48,897.84
                Phones         318,097.06     44,247.64
                Accessories    162,140.19     41,092.77
Office Supplies Paper           77,602.06     33,721.79
                Binders        203,060.33     30,143.04
Furniture       Chairs         319,593.36     26,503.94
Office Supplies Storage        222,016.71     21,010.29
                Appliances     105,977.65     17,872.44
Furniture       Furnishings     88,823.04     12,760.91
Office Supplies Envelopes       16,446.59      6,835.31
                Art             26,544.24      6,371.32
                Labels          12,346.69      5,528.05
Technology      Machines       188,789.53      4,028.47
Office Supplies Fasteners        2,983.85        918.03
                Supplies        46,561.05     -1,195.25
Furniture       Bookcases      113,567.76     -3,514.95
                Tables         202,250.14    -17,892.72

**Business Insight:** **Copiers and Phones** sit at the top for profit. But scroll to the bottom —
**Tables and Bookcases post a net loss** despite generating real sales. These are prime
candidates for a pricing or discount policy review.

In [86]:
loss_making_subcat = subcat_per[subcat_per['total_profit']<0]
loss_making_subcat

                              total_sales  total_profit
Category        Sub_Category
Office Supplies Supplies        46,561.05     -1,195.25
Furniture       Bookcases      113,567.76     -3,514.95
                Tables         202,250.14    -17,892.72

**Business Insight:** Only a small handful of sub-categories actually dip into negative
territory — a focused fix on just those few could meaningfully lift company-wide profit.

## 8. Business Question 3 — Top 10 Customers by Sales

**Business Scenario:** The account management team wants a VIP list — the customers who have
generated the most revenue over the years, so they can be prioritized for loyalty offers.

**What are we going to do?** Group by `Customer_Name`, sum Sales, sort, and take the top 10.

**Why is this important?** Retaining your highest-value customers is almost always cheaper than
acquiring new ones — you can't protect revenue you can't identify.

In [87]:
top_customer = df.groupby("Customer_Name")['Sales'].sum().sort_values(ascending=False).head(10)
top_customer

Customer_Name
Sean Miller          25,043.05
Tamara Chand         19,052.22
Raymond Buch         15,117.34
Tom Ashbrook         14,595.62
Adrian Barton        14,473.57
Ken Lonsdale         14,175.23
Sanjit Chand         14,142.33
Hunter Lopez         12,873.30
Sanjit Engle         12,209.44
Christopher Conant   12,129.07
Name: Sales, dtype: float64

**Business Insight:** The top customer alone has generated well over $10,000 in lifetime sales.
These 10 names are the retail equivalent of a VIP list — worth a dedicated account manager, not a
generic email blast.

## 9. Business Question 4 — Top 10 Products by Profit

**Business Scenario:** Inventory planning wants to know exactly which individual products to keep
stocked heavily going into next year.

**What are we going to do?** Group by `Product_Name`, sum Profit, sort descending, and take the
top 10.

**Why is this important?** Category-level insight (Section 7) tells us *where* to look;
product-level insight tells us *exactly what* to reorder.

In [88]:
top_products = df.groupby("Product_Name")['Profit'].sum().sort_values(ascending=False).head(10)
top_products

Product_Name
Canon imageCLASS 2200 Advanced Copier                                         18,479.95
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    7,753.04
Hewlett Packard LaserJet 3310 Copier                                           6,983.88
Canon PC1060 Personal Laser Copier                                             4,570.93
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      4,094.98
Ativa V4110MDD Micro-Cut Shredder                                              3,772.95
3D Systems Cube Printer, 2nd Generation, Magenta                               3,717.97
Plantronics Savi W720 Multi-Device Wireless Headset System                     3,696.28
Ibico EPK-21 Electric Binding System                                           3,345.28
Zebra ZM400 Thermal Label Printer                                              3,343.54
Name: Profit, dtype: float64

**Business Insight:** A single Canon copier is the single most profitable product in the entire
four-year history — a reminder that one hero SKU can matter more than an entire sub-category of
smaller items.

## 10. Business Question 5 — Which State Generated the Highest Revenue?

**Business Scenario:** The expansion team is deciding where to open the next physical showroom,
and wants to see revenue broken down by state.

**What are we going to do?** Group by `State`, sum Sales, and sort.

**Why is this important?** Geographic concentration tells a business where its customer base
actually is — critical for logistics, marketing spend, and expansion decisions.

In [89]:
state_sales = df.groupby("State")["Sales"].sum().sort_values(ascending=False)
state_sales.head(10)

State
California     449,984.87
New York       304,857.69
Texas          168,064.91
Washington     137,734.10
Pennsylvania   115,425.61
Florida         86,930.83
Illinois        79,463.98
Ohio            78,175.81
Michigan        75,451.44
Virginia        67,112.18
Name: Sales, dtype: float64

**Business Insight:** **California and New York** dominate state-level revenue by a wide margin
over every other state — unsurprising given their population, but it confirms coastal markets
are the backbone of this business.

## 11. Business Question 6 — Which Region Is the Most Profitable?

**Business Scenario:** Regional VPs are reviewed quarterly on profit, not just sales. Leadership
wants a clean region-by-category profit breakdown for that review.

**What are we going to do?** Build a `pivot_table()` of average and total Profit, sliced by
Region and Category at once.

**Why is this important?** A pivot table answers a two-dimensional business question ("which
region *and* which category?") in a single readable view — exactly the shape a business review
deck needs.

In [90]:
region_category_profit = pd.pivot_table(
    df,
    values = 'Profit',
    index = 'Region',
    columns = "Category",
    aggfunc = "sum"
)

In [91]:
region_category_profit['Total'] = region_category_profit.sum(axis=1)
region_category_profit.sort_values("Total",ascending=False)

Category  Furniture  Office Supplies  Technology     Total
Region
West      11,194.54        51,507.65   36,994.49 99,696.68
East       2,842.04        41,142.62   47,757.31 91,741.98
South      6,700.21        19,786.70   19,970.21 46,457.12
Central   -2,879.62         8,768.05   33,544.71 39,433.14

**Business Insight:** The **West region is the most profitable overall**, and Technology is the
strongest category in nearly every region — while Furniture drags down profit in more than one
region, echoing what we saw with Tables and Bookcases earlier.

## 12. Business Question 7 — Average Shipping Days

**Business Scenario:** Operations wants to know how many days, on average, pass between an order
being placed and it being shipped — a key customer-experience metric.

**What are we going to do?** Subtract `Order_Date` from `Ship_Date` using `apply()` and a
`lambda`, then average the result.

**Why is this important?** Shipping speed is one of the most direct levers a retailer has over
customer satisfaction — and it's simple to compute once both columns are true datetimes.

In [92]:
df['Shipping_Days'] = (df["Ship_Date"] - df["Order_Date"]).dt.days
average_shipping_days = df['Shipping_Days'].mean()
average_shipping_days

np.float64(3.958174904942966)

**Business Insight:** Shipping times vary order to order, but average out to just under 4 days —
a reasonable benchmark for operations to defend, or try to beat, next quarter.

## 13. Time Series Analysis — Setting the Foundation

**Business Scenario:** So far we've sliced the business by category, customer, product, and
region — all static cuts. But leadership's biggest question is usually simpler: **"Is the
business growing?"** That question can only be answered by looking at the data *over time*.

**What are we going to do?** Set `Order_Date` as the DataFrame's index, and sort the data
chronologically — the two prerequisites for every time series operation that follows.

**Why is this important?** Pandas' powerful time series tools (`resample`, rolling windows,
`pct_change`) all expect a `DatetimeIndex`. This is the single most important setup step in the
entire notebook.

In [93]:
ts = df.set_index("Order_Date").sort_index()
ts.head()

,Row ID,Order_ID,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,net_price_after_dis,Shipping_Days
Order_Date,,,,,,,,,,,,,,,,,,,,,
2014-01-03,7981,CA-2014-103800,2014-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,...,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.45,2,0.20,5.55,13.16,4
2014-01-04,740,CA-2014-112326,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.78,3,0.20,4.27,9.43,4
2014-01-04,741,CA-2014-112326,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.74,3,0.20,-64.77,218.19,4
2014-01-04,742,CA-2014-112326,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.54,2,0.80,-5.49,0.71,4
2014-01-05,1760,CA-2014-141817,2014-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,...,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.54,3,0.20,4.88,15.63,7

**Business Insight:** The index confirms our data spans **January 2014 through December 2017** —
four full years, exactly what we need for meaningful monthly, quarterly, and yearly trend
analysis.

## 14. Business Question 8 — Monthly Sales Trend

**Business Scenario:** The CFO's monthly board deck always starts with one table: total revenue,
month by month.

**What are we going to do?** `resample("ME")` the Sales column to monthly totals.

**Why is this important?** Monthly resampling is the workhorse of retail time series analysis —
it smooths day-to-day noise into a trend a business can actually act on.

In [94]:
monthly_sales = ts['Sales'].resample("ME").sum()
monthly_sales

Order_Date
2014-01-31    11,538.88
2014-02-28     4,519.89
2014-03-31    55,633.85
2014-04-30    27,679.92
2014-05-31    23,648.29
2014-06-30    34,501.02
2014-07-31    33,872.53
2014-08-31    27,879.66
2014-09-30    81,165.46
2014-10-31    31,453.39
2014-11-30    73,820.89
2014-12-31    67,270.78
2015-01-31    18,163.69
2015-02-28    11,860.53
2015-03-31    38,726.25
2015-04-30    33,052.73
2015-05-31    27,365.69
2015-06-30    23,032.43
2015-07-31    27,874.24
2015-08-31    36,760.33
2015-09-30    63,266.95
2015-10-31    31,404.92
2015-11-30    75,087.05
2015-12-31    74,607.09
2016-01-31    18,482.37
2016-02-29    22,947.57
2016-03-31    50,218.36
2016-04-30    37,276.50
2016-05-31    56,755.82
2016-06-30    39,752.40
2016-07-31    39,183.31
2016-08-31    30,781.80
2016-09-30    69,505.71
2016-10-31    59,572.86
2016-11-30    77,167.69
2016-12-31    95,006.99
2017-01-31    42,978.79
2017-02-28    20,219.21
2017-03-31    58,436.17
2017-04-30    36,398.58
2017-05-31    43,282.67
2017-06-30    52,624.71
2017-07-31    44,341.70
2017-08-31    63,108.02
2017-09-30    87,761.80
2017-10-31    77,638.28
2017-11-30   117,843.49
2017-12-31    80,857.05
Freq: ME, Name: Sales, dtype: float64

**Business Insight:** A clear seasonal pattern emerges in the numbers — **sales spike every
November/December** (holiday shopping) and dip in early months. Revenue also trends visibly
upward year over year, not just seasonally.

## 15. Business Question 9 — Monthly Profit Trend

**Business Scenario:** Sales going up is good news; but the board wants to know if **profit** is
keeping pace, or if the business is simply buying revenue with deeper discounts.

**What are we going to do?** Resample Profit to monthly totals, exactly like we did for Sales.

**Why is this important?** Comparing the Sales trend and Profit trend side by side is how you
catch a business that's growing revenue while quietly bleeding margin.

In [95]:
monthly_profit = ts['Profit'].resample("ME").sum()
loss_making_months = monthly_profit[monthly_profit < 0]

print(monthly_sales)
print(monthly_profit)

Order_Date
2014-01-31    11,538.88
2014-02-28     4,519.89
2014-03-31    55,633.85
2014-04-30    27,679.92
2014-05-31    23,648.29
2014-06-30    34,501.02
2014-07-31    33,872.53
2014-08-31    27,879.66
2014-09-30    81,165.46
2014-10-31    31,453.39
2014-11-30    73,820.89
2014-12-31    67,270.78
2015-01-31    18,163.69
2015-02-28    11,860.53
2015-03-31    38,726.25
2015-04-30    33,052.73
2015-05-31    27,365.69
2015-06-30    23,032.43
2015-07-31    27,874.24
2015-08-31    36,760.33
2015-09-30    63,266.95
2015-10-31    31,404.92
2015-11-30    75,087.05
2015-12-31    74,607.09
2016-01-31    18,482.37
2016-02-29    22,947.57
2016-03-31    50,218.36
2016-04-30    37,276.50
2016-05-31    56,755.82
2016-06-30    39,752.40
2016-07-31    39,183.31
2016-08-31    30,781.80
2016-09-30    69,505.71
2016-10-31    59,572.86
2016-11-30    77,167.69
2016-12-31    95,006.99
2017-01-31    42,978.79
2017-02-28    20,219.21
2017-03-31    58,436.17
2017-04-30    36,398.58
2017-05-31    43,282.67
2017-06-30    52,624.71
2017-07-31    44,341.70
2017-08-31    63,108.02
2017-09-30    87,761.80
2017-10-31    77,638.28
2017-11-30   117,843.49
2017-12-31    80,857.05
Freq: ME, Name: Sales, dtype: float64
Order_Date
2014-01-31    2,210.06
2014-02-28      862.31
2014-03-31      507.80
2014-04-30    3,893.09
2014-05-31    2,738.71
2014-06-30    4,977.95
2014-07-31     -842.79
2014-08-31    5,283.11
2014-09-30    8,297.04
2014-10-31    3,468.98
2014-11-30    9,371.62
2014-12-31    8,827.62
2015-01-31   -3,297.54
2015-02-28    2,813.85
2015-03-31    9,694.76
2015-04-30    4,295.62
2015-05-31    4,550.21
2015-06-30    3,233.41
2015-07-31    3,328.00
2015-08-31    5,326.33
2015-09-30    8,191.85
2015-10-31    2,805.13
2015-11-30   12,233.62
2015-12-31    7,896.31
2016-01-31    2,824.82
2016-02-29    4,960.17
2016-03-31    4,118.94
2016-04-30    2,858.24
2016-05-31    8,560.56
2016-06-30    4,620.17
2016-07-31    4,296.35
2016-08-31    2,062.07
2016-09-30    9,274.74
2016-10-31   16,236.59
2016-11-30    3,826.88
2016-12-31   17,824.22
2017-01-31    7,126.10
2017-02-28    1,613.87
2017-03-31    8,032.14
2017-04-30      605.99
2017-05-31    6,231.23
2017-06-30    8,094.90
2017-07-31    6,767.84
2017-08-31    8,968.29
2017-09-30   10,569.17
2017-10-31    9,221.28
2017-11-30    9,424.97
2017-12-31    8,542.35
Freq: ME, Name: Profit, dtype: float64

In [96]:
loss_making_months

Order_Date
2014-07-31     -842.79
2015-01-31   -3,297.54
Name: Profit, dtype: float64

**Business Insight:** Profit follows the same seasonal shape as Sales — but is far more volatile,
and **dips below zero in a few months**. Growing revenue does not automatically mean growing
profit; discounting and product mix both matter.

## 16. Business Questions 10 & 11 — Quarterly and Yearly Sales

**Business Scenario:** Investors don't read monthly numbers — they read quarterly and annual
ones. We need both views ready for the annual report.

**What are we going to do?** Resample Sales to quarterly (`"QE"`) and yearly (`"YE"`) frequency.

**Why is this important?** `resample()` uses the exact same syntax for every frequency — once you
know monthly, quarterly and yearly are free. This is the core "Resampling" concept for this
project.

In [97]:
quaterly_sales = ts["Sales"].resample("QE").sum()
yearly_sales = ts["Sales"].resample("YE").sum()

print(quaterly_sales)
print()
print(yearly_sales)

Order_Date
2014-03-31    71,692.62
2014-06-30    85,829.22
2014-09-30   142,917.65
2014-12-31   172,545.07
2015-03-31    68,750.47
2015-06-30    83,450.84
2015-09-30   127,901.52
2015-12-31   181,099.06
2016-03-31    91,648.29
2016-06-30   133,784.72
2016-09-30   139,470.81
2016-12-31   231,747.54
2017-03-31   121,634.17
2017-06-30   132,305.96
2017-09-30   195,211.53
2017-12-31   276,338.82
Freq: QE-DEC, Name: Sales, dtype: float64

Order_Date
2014-12-31   472,984.56
2015-12-31   461,201.90
2016-12-31   596,651.36
2017-12-31   725,490.48
Freq: YE-DEC, Name: Sales, dtype: float64

**Business Insight:** **Q4 of every single year is the strongest quarter**, confirming the
holiday-season effect is a real, repeating pattern. Sales have also **grown every year from 2014
to 2017** — solid top-line growth across the full history.

In [98]:
# Write your code here

**Business Insight:** Every year shows positive growth over the year before — confirming the
underlying trend beneath the quarterly seasonality is genuinely upward, not just a seasonal
illusion.

## 17. Business Questions 12 & 13 — Best and Worst Sales Months

**Business Scenario:** Marketing wants to know exactly which month to study for "what worked,"
and which month to study for "what went wrong."

**What are we going to do?** Use `sort_values()` on our `monthly_sales` Series to find the single
highest and lowest month.

**Why is this important?** Extremes are where the clearest business lessons live — the best month
shows you what peak demand looks like; the worst shows you the floor.

In [99]:
best_month = monthly_sales.sort_values(ascending=False).head(1)
worst_month = monthly_sales.sort_values(ascending=True).head(1)

print(best_month)
print(worst_month)

Order_Date
2017-11-30   117,843.49
Name: Sales, dtype: float64
Order_Date
2014-02-28   4,519.89
Name: Sales, dtype: float64

**Business Insight:** The best month is, unsurprisingly, a **November or December** — peak
holiday shopping. The worst month falls in **early-year territory (Jan/Feb)** — a natural
post-holiday lull worth planning inventory and cash flow around.

## 18. Business Question 14 — Rolling 30-Day Sales Average

**Business Scenario:** Daily sales are noisy — some days are simply slow because fewer orders
happened to land that day. Operations wants a smoothed signal to track the *underlying* trend day
by day, without the noise.

**What are we going to do?** Resample Sales to daily totals, then apply a 30-day rolling average.

**Why is this important?** A rolling average is the standard technique for smoothing volatile
daily data into a trend that's actually usable for forecasting or dashboards.

In [100]:
daily_sales = ts['Sales'].resample("D").sum()
rolling_30 = daily_sales.rolling(window=30).mean()
rolling_30

print(round(daily_sales.std(),2))
print(round(rolling_30.std(),2))

2201.87
752.4

**Business Insight:** The rolling average's standard deviation is far lower than daily sales' —
proof that it smooths out day-to-day noise while still tracking the same underlying holiday-season
climb we saw in the monthly numbers, making it the cleanest signal for forecasting or dashboards.

## 19. Business Question 15 — Cumulative Revenue

**Business Scenario:** Finance wants a single running total that shows exactly how much revenue
the business has booked from day one through today — the number investors expect in a growth
story.

**What are we going to do?** Apply `cumsum()` to the monthly sales Series.

**Why is this important?** A cumulative total is the cleanest way to demonstrate sustained growth
— it never goes down, so any slowdown in its pace is instantly visible when compared period to
period.

In [101]:
cum_sales = monthly_sales.cumsum()
cum_sales

Order_Date
2014-01-31      11,538.88
2014-02-28      16,058.77
2014-03-31      71,692.62
2014-04-30      99,372.54
2014-05-31     123,020.82
2014-06-30     157,521.84
2014-07-31     191,394.37
2014-08-31     219,274.03
2014-09-30     300,439.49
2014-10-31     331,892.88
2014-11-30     405,713.78
2014-12-31     472,984.56
2015-01-31     491,148.25
2015-02-28     503,008.78
2015-03-31     541,735.03
2015-04-30     574,787.76
2015-05-31     602,153.44
2015-06-30     625,185.87
2015-07-31     653,060.11
2015-08-31     689,820.44
2015-09-30     753,087.39
2015-10-31     784,492.31
2015-11-30     859,579.36
2015-12-31     934,186.45
2016-01-31     952,668.82
2016-02-29     975,616.39
2016-03-31   1,025,834.74
2016-04-30   1,063,111.25
2016-05-31   1,119,867.07
2016-06-30   1,159,619.46
2016-07-31   1,198,802.77
2016-08-31   1,229,584.57
2016-09-30   1,299,090.28
2016-10-31   1,358,663.14
2016-11-30   1,435,830.83
2016-12-31   1,530,837.81
2017-01-31   1,573,816.60
2017-02-28   1,594,035.82
2017-03-31   1,652,471.98
2017-04-30   1,688,870.56
2017-05-31   1,732,153.23
2017-06-30   1,784,777.95
2017-07-31   1,829,119.65
2017-08-31   1,892,227.67
2017-09-30   1,979,989.47
2017-10-31   2,057,627.75
2017-11-30   2,175,471.24
2017-12-31   2,256,328.29
Freq: ME, Name: Sales, dtype: float64

**Business Insight:** The final number is the total revenue booked across all four years — the
single top-line figure investors care about most.

## 20. Business Question 16 — Month-over-Month Growth

**Business Scenario:** Absolute sales numbers are useful, but leadership ultimately tracks
**growth rate** — "are we up or down versus last month, and by how much?"

**What are we going to do?** Apply `pct_change()` to the monthly sales Series.

**Why is this important?** `pct_change()` is the standard one-liner for turning any time series
into a growth-rate series — the single most quoted number in any monthly business review.

In [102]:
mom_growth = (monthly_sales.pct_change() * 100).round(2)
growth_dir = np.where(mom_growth >= 0,"Growth","Decline")
mom_summary = pd.DataFrame({"Growth%" : mom_growth, "Direction":growth_dir})

print(mom_summary)

            Growth% Direction
Order_Date
2014-01-31      NaN   Decline
2014-02-28   -60.83   Decline
2014-03-31 1,130.87    Growth
2014-04-30   -50.25   Decline
2014-05-31   -14.57   Decline
2014-06-30    45.89    Growth
2014-07-31    -1.82   Decline
2014-08-31   -17.69   Decline
2014-09-30   191.13    Growth
2014-10-31   -61.25   Decline
2014-11-30   134.70    Growth
2014-12-31    -8.87   Decline
2015-01-31   -73.00   Decline
2015-02-28   -34.70   Decline
2015-03-31   226.51    Growth
2015-04-30   -14.65   Decline
2015-05-31   -17.21   Decline
2015-06-30   -15.83   Decline
2015-07-31    21.02    Growth
2015-08-31    31.88    Growth
2015-09-30    72.11    Growth
2015-10-31   -50.36   Decline
2015-11-30   139.09    Growth
2015-12-31    -0.64   Decline
2016-01-31   -75.23   Decline
2016-02-29    24.16    Growth
2016-03-31   118.84    Growth
2016-04-30   -25.77   Decline
2016-05-31    52.26    Growth
2016-06-30   -29.96   Decline
2016-07-31    -1.43   Decline
2016-08-31   -21.44   Decline
2016-09-30   125.80    Growth
2016-10-31   -14.29   Decline
2016-11-30    29.53    Growth
2016-12-31    23.12    Growth
2017-01-31   -54.76   Decline
2017-02-28   -52.96   Decline
2017-03-31   189.01    Growth
2017-04-30   -37.71   Decline
2017-05-31    18.91    Growth
2017-06-30    21.58    Growth
2017-07-31   -15.74   Decline
2017-08-31    42.32    Growth
2017-09-30    39.07    Growth
2017-10-31   -11.54   Decline
2017-11-30    51.79    Growth
2017-12-31   -31.39   Decline

**Business Insight:** Growth swings wildly — some months post over 50% growth, others show a
sharp decline — confirming this business's revenue is **highly seasonal rather than steadily
growing**, and any single month-over-month number should be read with that context.

## 21. Sales Trend Analysis — Putting It All Together

**Business Scenario:** Leadership doesn't just want tables of numbers — they want the story those
numbers tell, in plain language.

**What are we going to do?** Summarize everything the time series section has shown us.

**Why is this important?** Numbers only become insight once someone translates them into a
decision. This is that translation.

**Business Insight — Sales Trend Summary:**

- Revenue is **strongly seasonal**, peaking every Q4 (Nov/Dec) and dipping every Jan/Feb.
- Despite the seasonality, **yearly totals have grown every year from 2014 to 2017**.
- The 30-day rolling average confirms this growth is a real underlying trend, not noise from a
  few lucky days.
- Month-over-month growth is volatile enough that no single month should be judged in isolation —
  always compare a month to the *same month* in a prior year, not just the month before it.

## 22. Business Question 17 — High Profit vs Low Profit Orders (np.where)

**Business Scenario:** Finance wants every order line tagged as either a "High Profit" or "Low
Profit" order, so they can quickly filter and audit the low-profit ones for discount abuse.

**What are we going to do?** Use `np.where()` to create a new label column based on a Profit
threshold, then use boolean indexing and `query()` to inspect each group.

In [103]:
profit_threshold = df['Profit'].median()
df['profit_level'] = np.where(df['Profit'] >= profit_threshold,"High Profit","low Profit")
df[["Sales","Profit","profit_level"]]

      Sales  Profit profit_level
0    261.96   41.91  High Profit
1    731.94  219.58  High Profit
2     14.62    6.87   low Profit
3    957.58 -383.03   low Profit
4     22.37    2.52   low Profit
...     ...     ...          ...
9989  25.25    4.10   low Profit
9990  91.96   15.63  High Profit
9991 258.58   19.39  High Profit
9992  29.60   13.32  High Profit
9993 243.16   72.95  High Profit

[9994 rows x 3 columns]

**Business Insight:** Roughly half the orders sit in each bucket (expected, since we split at the
median) — a simple, reusable flag Finance can filter on directly.

In [104]:
df['profit_level'].value_counts()

profit_level
High Profit    4997
low Profit     4997
Name: count, dtype: int64

In [105]:
low_profit_orders = df[df['profit_level'] == "low Profit"]
high_discount_low_profit = low_profit_orders.query("Discount >= 0.3")
high_discount_low_profit[["Product_Name","Discount","Profit"]].sort_values("Discount",ascending=False).head(10)

                                           Product_Name  Discount    Profit
15     Storex DuraTech Recycled Plastic Frosted Binders      0.80     -3.82
75                                      Economy Binders      0.80     -1.93
9920  GBC Pre-Punched Binding Paper, Plastic, White,...      0.80    -35.82
9795  Cardinal HOLDit! Binder Insert Strips,Extra St...      0.80     -5.89
9794                 Ibico Plastic Spiral Binding Combs      0.80    -31.01
9779   Acco 6 Outlet Guardian Standard Surge Suppressor      0.80    -12.09
9778       GBC Instant Index System for Binding Systems      0.80    -13.32
9776  GBC Premium Transparent Covers with Diagonal L...      0.80    -26.85
9774          GBC DocuBind P400 Electric Binding System      0.80 -3,701.89
5414                   Euro Pro Shark Stick Mini Vacuum      0.80   -197.58

**Business Insight:** A meaningful share of the lowest-profit orders were also **discounted 30% or
more** — strong evidence that overly aggressive discounting, not just cost or price, is a direct
driver of the company's unprofitable orders.

## 23. A Closer Look — loc & iloc in Practice

**Business Scenario:** An executive asks, mid-meeting, to see the full record for the single
highest-profit order, and separately, to see a specific slice of raw rows from the file.

**What are we going to do?** Use `loc` to fetch a row by a label/condition, and `iloc` to fetch
rows by raw position.

In [106]:
best_orders = df['Profit'].idxmax()
print("Highest profit order (using loc):\n", df.loc[best_orders])
print("\nFirst 5 raw rows (using iloc):\n", df.iloc[0:5])

Highest profit order (using loc):
 Row ID                                                  6827
Order_ID                                      CA-2016-118689
Order_Date                               2016-10-02 00:00:00
Ship_Date                                2016-10-09 00:00:00
Ship_Mode                                     Standard Class
Customer_ID                                         TC-20980
Customer_Name                                   Tamara Chand
Segment                                            Corporate
Country                                        United States
City                                               Lafayette
State                                                Indiana
Postal_Code                                            47905
Region                                               Central
Product_ID                                   TEC-CO-10004722
Category                                          Technology
Sub_Category                                         Copiers
Product_Name           Canon imageCLASS 2200 Advanced Copier
Sales                                              17,499.95
Quantity                                                   5
Discount                                                0.00
Profit                                              8,399.98
net_price_after_dis                                17,499.95
Shipping_Days                                              7
profit_level                                     High Profit
Name: 6826, dtype: object

First 5 raw rows (using iloc):
    Row ID        Order_ID Order_Date  Ship_Date       Ship_Mode Customer_ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

     Customer_Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

          Category Sub_Category  \
0        Furniture    Bookcases
1        Furniture       Chairs
2  Office Supplies       Labels
3        Furniture       Tables
4  Office Supplies      Storage

                                        Product_Name  Sales Quantity Discount  \
0                  Bush Somerset Collection Bookcase 261.96        2     0.00
1  Hon Deluxe Fabric Upholstered Stacking Chairs,... 731.94        3     0.00
2  Self-Adhesive Address Labels for Typewriters b...  14.62        2     0.00
3      Bretford CR4500 Series Slim Rectangular Table 957.58        5     0.45
4                     Eldon Fold 'N Roll Cart System  22.37        2     0.20

   Profit  net_price_after_dis  Shipping_Days  profit_level
0   41.91               261.96              3   High Profit
1  219.58               731.94              3   High Profit
2    6.87                14.62              4    low Profit
3 -383.03               526.67              7    low Profit
4    2.52                17.89              7    low Profit

[5 rows x 24 columns]

**Business Insight:** `loc` is how you pull up "the best order we've ever had" whenever
leadership asks; `iloc` is how you pull up "just show me a few raw rows" for a quick sanity
check.

## 24. Business Question 18 — Final Business Recommendations

Based on everything above, here is what we would tell Superstore's leadership team:

1. **Protect Q4.** Holiday-season demand (Nov/Dec) is the single biggest revenue driver every
   year — inventory and staffing plans should be built around it, not treated as a surprise.
2. **Review the discount policy on Furniture**, especially Tables and Bookcases — they generate
   real sales but post a net loss, most likely from over-discounting.
3. **Double down on Technology**, the strongest category for both sales and profit, and on the
   West region, the most profitable overall.
4. **Investigate orders discounted 30%+**, since they disproportionately show up among the
   lowest-profit orders in the business.
5. **Build a retention program around the top 10 customers** — they represent an outsized and
   easily identifiable share of lifetime revenue.

## 25. Final Summary

Over the course of this project we took a raw, four-year CSV export from a US retail chain and
turned it into a full business narrative:

- We **loaded and cleaned** the data — confirming its integrity, fixing types, and renaming
  columns for usability.
- We used **NumPy** directly on business arrays for uniqueness, sorting, broadcasting, and
  aggregation.
- We answered concrete **business questions** about category, sub-category, customer, product,
  state, and region performance using `groupby`, `agg`, and `pivot_table`.
- We built a full **time series pipeline**: datetime conversion, indexing, sorting, monthly /
  quarterly / yearly resampling, rolling averages, cumulative revenue, and month-over-month growth.
- We closed by combining `np.where()`, boolean indexing, and `query()` to flag and investigate
  unprofitable orders — turning analysis into an actionable recommendation.

This is exactly the workflow a retail analyst runs every single reporting cycle — you now have a
template you can point at any transaction-level dataset.

## 26. Ten Business Insights

1. Technology, Furniture, and Office Supplies contribute fairly evenly to total sales — this is a
   diversified business, not a single-category one.
2. Copiers and Phones are the most profitable sub-categories; Tables and Bookcases post a net
   loss.
3. A small group of top customers account for a disproportionate share of lifetime revenue.
4. A single hero product (a Canon copier) is the most profitable individual product in company
   history.
5. California and New York are the company's two largest state markets by a wide margin.
6. The West region is the most profitable overall; Furniture drags profit down in more than one
   region.
7. Average shipping time sits just under 4 days company-wide.
8. Sales are strongly seasonal, peaking every Q4 and dipping every Jan/Feb — a pattern that
   repeats every single year in the dataset.
9. Yearly revenue has grown every year from 2014 to 2017, even though month-to-month growth is
   volatile.
10. Orders discounted 30% or more are disproportionately represented among the lowest-profit
    orders — discounting policy is a direct, fixable lever on profit.

## 27. Ten Practice Questions for Students

Try these on your own, reusing the techniques from this notebook:

1. Which `Segment` (Consumer, Corporate, Home Office) generates the highest average order value?
2. Which `Ship_Mode` is used most often, and does it correlate with shipping days?
3. Find the top 5 cities by total profit using `groupby()` and `sort_values()`.
4. Build a `pivot_table()` of average Discount by Category and Segment.
5. Use `np.where()` to flag orders with `Quantity` greater than 5 as "Bulk Orders."
6. Resample Profit to weekly totals — what does the seasonality look like at that resolution?
7. Calculate a 7-day rolling average of Sales instead of 30-day. How much noisier is it?
8. Use `query()` to find all orders in the "West" region with Profit below zero.
9. Compute quarter-over-quarter growth using `pct_change()` on the quarterly Sales Series.
10. Using `apply()` and a `lambda`, create a new column classifying each order as "Fast Shipping"
    (2 days or fewer) or "Standard Shipping."

---
*End of Project — Retail Sales Analysis using NumPy, Pandas & Time Series*

Which Segment (Consumer, Corporate, Home Office) generates the highest average order value?

In [107]:
avg_order_value = df.groupby('Segment')['Sales'].mean().sort_values(ascending=False)
display(avg_order_value)

Segment
Home Office   235.75
Corporate     230.78
Consumer      219.42
Name: Sales, dtype: float64

**Which Ship_Mode is used most often, and does it correlate with shipping days?**

In [108]:
# 1. Which Ship_Mode is used most often?
ship_mode_counts = df['Ship_Mode'].value_counts()
display(ship_mode_counts)

# 2. Does it correlate with shipping days?
ship_mode_days = df.groupby('Ship_Mode')['Shipping_Days'].mean().sort_values()
display(ship_mode_days)

Ship_Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

Ship_Mode
Same Day         0.04
First Class      2.18
Second Class     3.24
Standard Class   5.01
Name: Shipping_Days, dtype: float64

**Find the top 5 cities by total profit using groupby() and sort_values().**

In [115]:
top_cities = df.groupby("City")['Profit'].sum().sort_values(ascending=False)
top_cities.head(5)

City
New York City   61,699.87
Los Angeles     30,148.63
Seattle         22,051.26
San Francisco   16,605.78
Detroit         13,177.03
Name: Profit, dtype: float64

Build a pivot_table() of average Discount by Category and Segment.

**Build a pivot_table() of average Discount by Category and Segment.**

In [117]:
avg_dics = pd.pivot_table(
    df,
    values = 'Discount',
    index = "Category",
    columns = "Segment",
    aggfunc = "mean"
)

avg_dics

Segment          Consumer  Corporate  Home Office
Category
Furniture            0.18       0.17         0.17
Office Supplies      0.16       0.16         0.15
Technology           0.13       0.13         0.13

```markdown
**5. Use np.where() to flag orders with Quantity greater than 5 as "Bulk Orders."**
```

In [119]:
df['Order_Type'] = np.where(df['Quantity'] > 5, 'Bulk Order', 'Standard Order')
df[['Order_ID', 'Quantity', 'Order_Type']].head(10)

         Order_ID  Quantity      Order_Type
0  CA-2016-152156         2  Standard Order
1  CA-2016-152156         3  Standard Order
2  CA-2016-138688         2  Standard Order
3  US-2015-108966         5  Standard Order
4  US-2015-108966         2  Standard Order
5  CA-2014-115812         7      Bulk Order
6  CA-2014-115812         4  Standard Order
7  CA-2014-115812         6      Bulk Order
8  CA-2014-115812         3  Standard Order
9  CA-2014-115812         5  Standard Order

In [120]:
df.head()

,Row ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,net_price_after_dis,Shipping_Days,profit_level,Order_Type
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,261.96,3,High Profit,Standard Order
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,731.94,3,High Profit,Standard Order
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,14.62,4,low Profit,Standard Order
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03,526.67,7,low Profit,Standard Order
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,17.89,7,low Profit,Standard Order

**Resample Profit to weekly totals — what does the seasonality look like at that resolution?**

In [124]:
weekly_profit = ts["Profit"].resample("W").sum()
display(weekly_profit.head())
display(weekly_profit.tail())

Order_Date
2014-01-05     -55.55
2014-01-12   1,321.26
2014-01-19     160.23
2014-01-26     758.04
2014-02-02     239.55
Freq: W-SUN, Name: Profit, dtype: float64

Order_Date
2017-12-03   2,078.47
2017-12-10   1,099.17
2017-12-17     758.96
2017-12-24   4,317.34
2017-12-31   1,377.93
Freq: W-SUN, Name: Profit, dtype: float64

**Calculate a 7-day rolling average of Sales instead of 30-day. How much noisier is it?**

In [126]:
daily_sales = ts['Sales'].resample("D").sum()
rolling_7 = daily_sales.rolling(window=7).mean()

print("Daily Sales Std Dev:", round(daily_sales.std(), 2))
print("30-day Rolling Avg Std Dev:", round(rolling_30.std(), 2))
print("7-day Rolling Avg Std Dev:", round(rolling_7.std(), 2))
display(rolling_7)

Daily Sales Std Dev: 2201.87
30-day Rolling Avg Std Dev: 752.4
7-day Rolling Avg Std Dev: 1042.45

Order_Date
2014-01-03        NaN
2014-01-04        NaN
2014-01-05        NaN
2014-01-06        NaN
2014-01-07        NaN
               ...
2017-12-26   3,024.57
2017-12-27   2,995.98
2017-12-28   2,926.90
2017-12-29   2,224.03
2017-12-30   2,103.32
Freq: D, Name: Sales, Length: 1458, dtype: float64

**Use query() to find all orders in the "West" region with Profit below zero.**

In [128]:
west_region_low_profit_orders = df.query("Region == 'West' and Profit < 0")
display(west_region_low_profit_orders.head())

,Row ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,net_price_after_dis,Shipping_Days,profit_level,Order_Type
95,96,US-2017-109484,2017-11-06,2017-11-12,Standard Class,RB-19705,Roger Barcio,Home Office,United States,Portland,...,Binders,Flexible Leather- Look Classic Collection Ring...,5.68,1,0.70,-3.79,1.70,6,low Profit,Standard Order
103,104,US-2015-156867,2015-11-13,2015-11-17,Standard Class,LC-16870,Lena Cacioppo,Consumer,United States,Aurora,...,Accessories,Logitech K350 2.4Ghz Wireless Keyboard,238.90,6,0.20,-26.88,191.12,4,low Profit,Bulk Order
104,105,US-2015-156867,2015-11-13,2015-11-17,Standard Class,LC-16870,Lena Cacioppo,Consumer,United States,Aurora,...,Furnishings,"Deflect-o DuraMat Lighweight, Studded, Beveled...",102.36,3,0.20,-3.84,81.89,4,low Profit,Standard Order
105,106,US-2015-156867,2015-11-13,2015-11-17,Standard Class,LC-16870,Lena Cacioppo,Consumer,United States,Aurora,...,Binders,"Avery Trapezoid Ring Binder, 3"" Capacity, Blac...",36.88,3,0.70,-25.82,11.06,4,low Profit,Standard Order
126,127,US-2017-107272,2017-11-05,2017-11-12,Standard Class,TS-21610,Troy Staebel,Consumer,United States,Phoenix,...,Binders,"Avery Durable Slant Ring Binders, No Labels",2.39,2,0.70,-1.83,0.72,7,low Profit,Standard Order

**Compute quarter-over-quarter growth using pct_change() on the quarterly Sales Series.**

In [129]:
qoq_growth = quaterly_sales.pct_change() * 100
display(qoq_growth)

Order_Date
2014-03-31      NaN
2014-06-30    19.72
2014-09-30    66.51
2014-12-31    20.73
2015-03-31   -60.16
2015-06-30    21.38
2015-09-30    53.27
2015-12-31    41.59
2016-03-31   -49.39
2016-06-30    45.98
2016-09-30     4.25
2016-12-31    66.16
2017-03-31   -47.51
2017-06-30     8.77
2017-09-30    47.55
2017-12-31    41.56
Freq: QE-DEC, Name: Sales, dtype: float64

**Using apply() and a lambda, create a new column classifying each order as "Fast Shipping" (2 days or fewer) or "Standard Shipping**

In [133]:
df['Shipping_Class'] = df['Shipping_Days'].apply(lambda x: 'Fast Shipping' if x <= 2 else 'Standard Shipping')
display(df[['Shipping_Days', 'Shipping_Class']].head())

   Shipping_Days     Shipping_Class
0              3  Standard Shipping
1              3  Standard Shipping
2              4  Standard Shipping
3              7  Standard Shipping
4              7  Standard Shipping

---

### Practice Question: Classify Orders by Profitability

**Using `apply()` and a `lambda`, create a new column called 'Profitability_Status' that classifies each order as "Profitable" (Profit > 0) or "Unprofitable" (Profit <= 0). Then display the 'Profit', 'Profitability_Status', and 'Sales' columns for the first 10 rows.**

In [134]:
df['Profitability_Check'] = df['Profit'].apply(lambda x:'Profitable' if x > 0 else 'Unprofitable')
df[["Profit","Profitability_Check"]].head()

   Profit Profitability_Check
0   41.91          Profitable
1  219.58          Profitable
2    6.87          Profitable
3 -383.03        Unprofitable
4    2.52          Profitable

Index(['Row ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State',
       'Postal_Code', 'Region', 'Product_ID', 'Category', 'Sub_Category',
       'Product_Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'net_price_after_dis', 'Shipping_Days', 'profit_level', 'Order_Type',
       'Shipping_Class', 'Profitability_Check'],
      dtype='object')